title: hol-jud18
description: malware dev // security research // low-level systems
url: "https://hol-jud18.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
